# ------------------------------------------------------------------------------
# nginx/tasks/fail2ban.yml
# ------------------------------------------------------------------------------

# This task list installs the fail2ban service on an Nginx host.

---

- block:

    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        install_recommends: no

    - name: Template out the jail.local file
      ansible.builtin.template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify: Fail2Ban configuration changed

    - name: Copy the default filter configuration file
      ansible.builtin.copy:
        src: default-filter.conf
        dest: /etc/fail2ban/filter.d/varilink-default.conf
      notify: Fail2Ban configuration changed

    - name: Copy the http and noop action configuration files
      ansible.builtin.copy:
        src: "{{ item }}-action.conf"
        dest: "/etc/fail2ban/action.d/varilink-{{ item }}.conf"
      notify: Fail2Ban configuration changed
      loop:
        - http
        - noop

    - name: Copy the default jail configuration file
      ansible.builtin.copy:
        src: default-jail.conf
        dest: /etc/fail2ban/jail.d/varilink-default.conf
      notify: Fail2Ban configuration changed

    - name: Copy the WordPress red and amber filter configuration files
      ansible.builtin.copy:
        src: "wordpress-{{ item }}-filter.conf"
        dest: "/etc/fail2ban/filter.d/varilink-wordpress-{{ item }}.conf"
      loop:
        - red
        - amber

  become: yes