- block:

    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        install_recommends: no

    - name: Template out the jail.local file
      ansible.builtin.template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify: Fail2Ban configuration changed

    - name: Copy the varilink-wordpress jail configuration file
      ansible.builtin.copy:
        src: varilink-wordpress-jail.conf
        dest: /etc/fail2ban/jail.d/varilink-wordpress.conf
      notify: Fail2Ban configuration changed

    - name: Copy varilink-noop.conf action configuration file
      ansible.builtin.copy:
        src: varilink-noop-action.conf
        dest: /etc/fail2ban/action.d/varilink-noop.conf
      notify: Fail2Ban configuration changed

    - name: Copy varilink-wordpress-filter filter configuration file
      ansible.builtin.copy:
        src: varilink-wordpress-filter.conf
        dest: /etc/fail2ban/filter.d/varilink-wordpress.conf
      notify: Fail2Ban configuration changed

  become: yes