# ------------------------------------------------------------------------------
# nginx/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- name: Install APT packages for Nginx role
  ansible.builtin.apt:
    name:
      - nginx
      - ssl-cert
    install_recommends: no
  become: yes
