# ------------------------------------------------------------------------------
# nginx/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- name: Install APT packages for Nginx role
  ansible.builtin.apt:
    name: nginx
    install_recommends: no
  become: yes
