# ------------------------------------------------------------------------------
# mail_internal/tasks/configure-service/exim-smtp-outbound.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Add a REQUIRE_PROTOCOL section to config template for remote SMTP
      ansible.builtin.blockinfile:
        path: /etc/exim4/conf.d/transport/30_exim4-config_remote_smtp
        block: |-
          .ifdef REQUIRE_PROTOCOL
            protocol = REQUIRE_PROTOCOL
          .endif
      notify: Exim configuration changed

    # This may be a duplicate for the task "Add line to /etc/exim4/passwd.client
    # if credentials supplied" which is in the configure-service.yml task list
    # of the mta role.
    - name: >-
        Add a line to the passwd.client file for authentication to the
        mail_external smarthost
      ansible.builtin.lineinfile:
        path: /etc/exim4/passwd.client
        line: "\
          {{ mta_smarthost.hostname }}:\
          {{ mta_smarthost.username }}:\
          {{ mta_smarthost.userpass }}"

  become: yes
