# ------------------------------------------------------------------------------
# mail_internal/tasks/configure-services/fetchmail.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Make fetchmail run in daemon mode
      ansible.builtin.lineinfile:
        path: /etc/default/fetchmail
        regexp: '^START_DAEMON=(?:yes|no)$'
        line: START_DAEMON=yes
      notify: Fetchmail configuration changed

    - name: Add the interval option for fetchmail
      ansible.builtin.lineinfile:
        path: /etc/default/fetchmail
        regexp: '^(?:# )?OPTIONS=(?:...|"-d 10")$'
        line: OPTIONS="-d 10"
      notify: Fetchmail configuration changed

    - name: Deploy fetchmailrc file
      ansible.builtin.template:
        src: fetchmailrc.j2
        dest: /etc/fetchmailrc
        owner: fetchmail
        mode: 0600
      vars:
        target_host: |-
          {% for host, roles in hosts_to_roles_map.items() %}
          {% if 'mail_external' in roles %}
          {{ host }}
          {%- endif %}
          {% endfor %}
        users: "{{ domain_users }}"
      notify: Fetchmail configuration changed

  become: yes
