# ------------------------------------------------------------------------------
# mail_internal/tasks/configure-service.yml
# ------------------------------------------------------------------------------

---

- block:

    - ansible.builtin.import_tasks: configure-service/fetchmail.yml

    - ansible.builtin.import_tasks: configure-service/exim-smtp-outbound.yml

    - ansible.builtin.import_tasks: configure-service/local-delivery.yml

    - ansible.builtin.import_tasks: configure-service/dovecot.yml

    - ansible.builtin.import_tasks: configure-service/roundcube.yml

    - ansible.builtin.include_tasks: user.yml
      loop: "{{ domain_users }}"
      loop_control:
        loop_var: user

  become: yes
