# ------------------------------------------------------------------------------
# mail/tasks/configure-service.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Set Dovecot mail location to Maildir
      ansible.builtin.lineinfile:
        path: /etc/dovecot/conf.d/10-mail.conf
        line: mail_location = maildir:~/Maildir
        regexp: '^mail_location = '
      notify: Dovecot configuration changed

    - name: Roundcube smtp_host config setting
      # Roundcube uses port 587 by default but we prefer 25 for trusted,
      # unauthenticated and unecrypted connections on the localhost interface.
      ansible.builtin.lineinfile:
        path: /etc/roundcube/config.inc.php
        line: "$config['smtp_host'] = 'localhost:25';"
        regexp: "^\\$config\\['smtp_host'\\] = '.*';$"

    - name: Roundcube support_url config setting
      ansible.builtin.lineinfile:
        path: /etc/roundcube/config.inc.php
        line: "\
          $config['support_url'] = 'https://{{ domain_name }}/roundcube/';"
        regexp: "^\\$config\\['support_url'\\] = '.*';$"

    - name: Roundcube product_name config setting
      ansible.builtin.lineinfile:
        path: /etc/roundcube/config.inc.php
        line: "$config['product_name'] = 'Varilink Webmail';"
        regexp: "^\\$config\\['product_name'\\] = '.*';$"

    - name: Roundcube des_key config setting
      # This task generates a new, random DES key each time it is executed.
      # Therefore it will always report a change, since the new key replaces
      # any key that was previously in the file.
      ansible.builtin.lineinfile:
        path: /etc/roundcube/config.inc.php
        line: "$config['des_key'] = '{{ des_key }}';"
        regexp: "^\\$config\\['des_key'\\] = '.*';$"
      vars:
        des_key: >-
          {{
            query('community.general.random_string', length=24, special=false)
            | first
          }}

    - name: Add BEGIN block marker for plugins config setting
      ansible.builtin.lineinfile:
        path: /etc/roundcube/config.inc.php
        line: '# BEGIN ANSIBLE MANAGED BLOCK'
        insertafter: '^// Debian: install roundcube-plugins first to have any$'

    - name: Add END block marker for plugins config setting
      ansible.builtin.lineinfile:
        path: /etc/roundcube/config.inc.php
        line: '# END ANSIBLE MANAGED BLOCK'
        insertbefore: '^// skin name: folder from skins/$'

    - name: Roundcude plugins config setting
      ansible.builtin.blockinfile:
        path: /etc/roundcube/config.inc.php
        block: |-
          $config['plugins'] = [
            // 'archive',
            // 'zipdownload',
            'managesieve'
          ];

    - name: Replace the Roundcube logo with our own
      ansible.builtin.copy:
        src: logo.svg
        dest: /var/lib/roundcube/skins/elastic/images/logo.svg

    - name: Drop rather than deny in the Exim check data ACL
      ansible.builtin.replace:
        path: /etc/exim4/conf.d/acl/40_exim4-config_check_data
        regexp: '(\.ifn?def {{ target_block }}[\s\S]*?\n)\s*deny\b'
        replace: '\1 drop'
      loop:
        - IGNORE_SMTP_LINE_LENGTH_LIMIT
        - NO_CHECK_DATA_VERIFY_HEADER_SYNTAX
        - CHECK_DATA_VERIFY_HEADER_SENDER
      loop_control:
        loop_var: target_block

  become: yes
