# ------------------------------------------------------------------------------
# mail/tasks/create-user.yml
# ------------------------------------------------------------------------------

# Both the mail_external and mail_internal roles must create operating system
# accounts for each of the staff users within the home domain. For the home
# domain, mail users are implemented as operating system users rather than as
# virtual mail users, which is what we do for customer domains. This task list
# provides a common mail wrapper for any tasks that both the mail_external and
# mail_internal roles must incorporate when doing this.

---

- block:

    - ansible.builtin.import_role:
        name: staff_user

    - name: Add alias for user to the /etc/aliases file
      ansible.builtin.lineinfile:
        path: /etc/aliases
        line: '{{ username }}.{{ user.lname | lower }}: {{ username }}'
      become: yes
      notify: Aliases changed

  vars:
    username: "{{ user.fname | lower }}"
    password: "{{ user.password }}"
  when: domain_name == home_domain
