# ------------------------------------------------------------------------------
# backup_director/tasks/configure-service.yml
# ------------------------------------------------------------------------------

---

- name: Give members of the bacula group access to the bacula home folder
  ansible.builtin.file:
    path: /var/lib/bacula
    mode: u=rwx,g=rx,o=
  become: yes

# The backup director is configured to backup one of:
# 1. Hosts in the inventory group backup_clients.
# 2. All hosts apart from those in the inventory group backup_exceptions.
# 3. All hosts.
#
# Either backup_clients or backup_exceptions or neither should be configured as
# inventory groups. It's not valid for both backup_clients and backup_exceptions
# to be configured as inventory groups.
#
# The backup_client role must be allocated in plays that match the following
# host patterns in those three scenarios:
# 1. backup_clients
# 2. all:!backup_exceptions
# 3. all

- name: >-
    Derive hosts in backup_clients and backup_exceptions inventory groups
  ansible.builtin.set_fact:
    backup_clients: "\
      {{ groups['backup_clients'] | default('[]') }}"
    backup_exceptions: "\
      {{ groups['backup_exceptions'] | default('[]') }}"

- name: >-
    Fail if there are hosts in both backup_clients and backup_exceptions
    inventory groups
  ansible.builtin.fail:
    msg: >-
      It's not valid to have both backup_clients and backup_exceptions
      groups in your inventory
  when: backup_clients | length > 0 and backup_exceptions | length > 0

- name: Discover all the role Bacula Fileset var files for roles in our library
  local_action:
    module: ansible.builtin.find
    paths: [ "{{ role_path }}/.." ]
    patterns: [ "bacula-fileset.yml" ]
    recurse: yes
  register: fileset_find_result

# The following three tasks convert the contents of the vars/bacula-fileset.yml
# files into the following two variables that are used in the bacula-dir.conf.j2
# template.
#
# role_fileset_file_lists
# A dictionary variable with keys that are the names of roles that define a list
# of values for one or more "File" FileSet directives that are to be wrapped in
# a role specific FileSet "Include" directive for hosts that role is deployed
# to.
#
# role_fileset_include_lists
# A dictionary variable with keys that are the names of roles that define a list
# of the names of one or more other roles whose FileSet configuration is to be
# concatenated into the FileSet configuration of the parent role.
#
# There are intermediate variables created along the way that are NOT used in
# the vars/bacula-fileset.yml

- name: >-
    Load the contents of the bacula-file.yml files into the role_fileset_specs
    variable
  ansible.builtin.include_tasks: ./bacula-filesets/load-vars.yml
  vars:
    file_path: "{{ item.path }}"
    fileset_role: "{{ file_path | dirname | dirname | basename }}"
  loop: "{{ fileset_find_result.files }}"

- name: Set a fact containing FileSet file lists for all roles that have them
  # The fact is role_fileset_file_lists and it contains keys that are the names
  # of the roles that specify an included_files list and values that are the
  # lists corresponding to each of the roles.
  ansible.builtin.set_fact:
    role_fileset_file_lists: >-
      {{
        role_fileset_file_lists | default({}) | combine(role_fileset_file_list)
      }}
  vars:
    role_fileset_file_list: >-
      {{
        {
          fileset_role_name :
            role_fileset_specs[fileset_role_name].included_files
        }
      }}
  loop: "{{ role_fileset_specs.keys() | list }}"
  loop_control:
    loop_var: fileset_role_name
  when: role_fileset_specs[fileset_role_name].included_files is defined

- name: Build the role_fileset_include_lists variable
  # The role_fileset_include_lists variable contains keys that are the names of
  # the roles and values that are a list of all other roles that must be
  # included with the key role.
  ansible.builtin.include_tasks: ./bacula-filesets/parent-role.yml
  loop: "{{ role_fileset_specs.keys() | list }}"
  loop_control:
    loop_var: parent_role
  when: role_fileset_specs[parent_role].included_roles is defined

- block:

    - name: Template bacula-dir.conf
      ansible.builtin.template:
        src: bacula-dir.conf.j2
        dest: /etc/bacula/bacula-dir.conf
        owner: root
        group: bacula
        mode: 0640
      vars:
        # hostnames = the hosts to be backup up - see above.
        hostnames: |-
          {% if backup_clients | length > 0 %}
          {{ backup_clients }}
          {% elif backup_exceptions | length > 0 %}
          {{ query('inventory_hostnames', 'all:!backup_exceptions') }}
          {% else %}
          {{ query('inventory_hostnames', 'all') }}
          {% endif %}
      notify: Bacula director configuration changed

    - name: Determine if a folder has been created for Dropbox integration
      ansible.builtin.stat:
        path: /var/lib/bacula/Dropbox
      register: dropbox_dir

    - name: >-
        Ensure the Bootstrap folder is present in the Dropbox folder if the
        Dropbox folder exists
      ansible.builtin.file:
        path: /var/lib/bacula/Dropbox/{{ backup_copy_folder }}/Bootstrap
        state: directory
        owner: bacula
        group: bacula
      when: dropbox_dir.stat.exists and dropbox_dir.stat.isdir

    - name: >-
        Ensure the Bootstrap folder is present directly in the bacula home
        directory if the Dropbox folder doesn't exist
      ansible.builtin.file:
        path: /var/lib/bacula/Bootstrap
        state: directory
        owner: bacula
        group: bacula
      when: not dropbox_dir.stat.exists

    - name: Copy the bacula catalog queries file to the director host
      ansible.builtin.copy:
        src: query.sql
        dest: /etc/bacula/scripts/query.sql

  become: yes
