# ------------------------------------------------------------------------------
# dns/tasks/create-record.yml
# ------------------------------------------------------------------------------

# This task creates a DNS record in the internal/office DNS service, which is
# implemented using Dnsmasq. The caller MUST provide a value for
# dns_record_hostname, which is the name that will be used for the DNS record.
#
# The variable dns_record_inventory_host is optional; if it is provided it must
# be the name of the host in the Ansible inventory that is the target of the
# lookup, if it isn't provided then the current play host is used. The target
# inventory host is used to determine the "ansible_default_ipv4.address" to use
# for the DNS record.
#
# The caller can also optionally pass a variable "dns_record_group", which can
# take the values "host", "service" or "project". This is used to control the
# section within the `/etc/add-hosts` file where the record is inserted.

---

- name: >-
    Gather the IPv4 address for the DNS record inventory host if it isn't
    already known
  ansible.builtin.setup:
    gather_subset:
      - 'default_ipv4'
  delegate_to: "{{ dns_record_inventory_host }}"
  delegate_facts: true
  when: >-
    dns_record_inventory_host is defined and
    hostvars[dns_record_inventory_host].ansible_default_ipv4 is not defined

- name: Create DNS record
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: |-
      {% if dns_record_inventory_host is defined %}
      {{ hostvars[dns_record_inventory_host].ansible_default_ipv4.address }}
      {%- else %}
      {{ ansible_default_ipv4.address }}
      {%- endif %}
      {%- if dns_record_group is defined and dns_record_group == 'project' %}
       {{ dns_record_hostname }}.{{ domain_name }}
      {%- else %}
       {{ dns_record_hostname }}
      {%- endif %}
    insertafter: |-
      {% if dns_record_group is not defined %}
      EOF
      {%- elif dns_record_group == 'host' %}
      ^# Hosts$
      {%- elif dns_record_group == 'service' %}
      ^# Services$
      {%- elif dns_record_group == 'project' %}
      ^# Projects$
      {%- else %}
      EOF
      {% endif %}
    regexp: |-
      {%- if dns_record_group is defined and dns_record_group == 'project' %}
      {{
        '^192\.168\.1\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)'
        ~ dns_record_hostname ~ '.' ~ domain_name ~ '$'
      }}
      {%- else %}
      {{
        '^192\.168\.1\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d) '
        ~ dns_record_hostname ~ '$'
      }}
      {%- endif %}
  notify: Dnsmasq configuration changed
  become: yes
