# ------------------------------------------------------------------------------
# dns/tasks/delete-site.yml
# ------------------------------------------------------------------------------

---

- name: Remove DNS entries for WordPress site
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: >-
      {{
        hostvars[wp_host].ansible_default_ipv4.address
          | default(ansible_default_ipv4.address)
      }}
      {{ wp_server_name }}
    state: absent
  notify: Dnsmasq configuration changed
  become: yes
