# ------------------------------------------------------------------------------
# dns/tasks/delete-record.yml
# ------------------------------------------------------------------------------

# Delete a DNS record, which in respect of this role equates to deleting a
# record from the /etc/addn-hosts file on the host for the dnsmasq service on
# the office network, and restarting that service for the deletion to take
# effect.

---

- name: Delete DNS record
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: |-
      {% if dns_record_target is defined %}
      {{ hostvars[dns_record_target].ansible_default_ipv4.address }}
      {%- else %}
      {{ ansible_default_ipv4.address }}
      {%- endif %} {{ dns_record_hostname }}
    state: absent
  notify: Dnsmasq configuration changed
  become: yes
