- name: Deploy the backup storage role
  become: yes
  block:

    - name: Add buster backports to the sources list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: deb http://deb.debian.org/debian buster-backports main

    - name: Update the APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install apt package(s) required for the backup storage role
      ansible.builtin.apt:
        name:
          - bacula-bscan
          - bacula-common-mysql
          - bacula-sd
        install_recommends: no
        default_release: buster-backports

    - name: Create folder for storage archive
      ansible.builtin.file:
        group: bacula
        owner: bacula
        path: /var/local/bacula
        state: directory

    - name: Template out the bacula-sd.conf for the backup server
      ansible.builtin.template:
        src: "templates/bacula-sd.conf.j2"
        dest: /etc/bacula/bacula-sd.conf
        mode: '0640'
        owner: root
        group: bacula
      notify: bacula storage daemon configuration changed

    - name: Install and setup Dropbox for backup use
      ansible.builtin.import_role:
        name: backup_dropbox
