# ------------------------------------------------------------------------------
# nginx/files/default-filter.conf
# ------------------------------------------------------------------------------

# Filter used for the Nginx default website. This filter should catch ALL
# requests for the default website as the presumption is that none of them can
# be valid.

# ------

[Definition]

failregex =
    ^<HOST> .* "\S+ [^"]+ HTTP/[0-9.]+"

ignoreregex =
