# ------------------------------------------------------------------------------
# nginx/files/default-jail.conf
# ------------------------------------------------------------------------------

# Jail used for the Nginx default website. The presumption that is the basis of
# this jail is that there is no valid reason why any requests should be received
# for the Nginx default website.

# ------

[varilink-default]

enabled  = true
filter   = varilink-default

logpath  = /var/log/nginx/access.log

maxretry = 1
findtime = 10m
bantime  = 1h

action   = varilink-noop
