[INCLUDES]

before = nftables.conf


[Definition]

actionban = <nftables> add element <table_family> <table> <addr_set> \
            \{ <ip> \} \
            && logger -t varilink-http \
            "BANNED <ip> in jail <name>"

actionunban = <nftables> delete element <table_family> <table> <addr_set> \
              \{ <ip> \} \
              && logger -t varilink-http \
              "UNBANNED <ip> in jail <name>"


[Init]

type = multiport
port = 80,443
protocol = tcp
