[Definition]

failregex =
    ^<HOST> .* "(?:GET|POST) /wp-login\.php(?:\?.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /xmlrpc\.php(?:\?.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /wp-admin(?:/.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /wp-content/plugins/[^ ]+ HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /wp-content/themes/[^ ]+ HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /(?:\.env|wp-config\.php|phpmyadmin)(?:/.*)? HTTP/.*"

ignoreregex =
