[Definition]

failregex =
    ^<HOST> .* "(?:GET|POST) /\.env(?:/.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /wp-config\.php(?:/.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /phpmyadmin(?:/.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /xmlrpc\.php(?:\?.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /readme\.html(?:\?.*)? HTTP/.*"
    ^<HOST> .* "(?:GET|POST) /license\.txt(?:\?.*)? HTTP/.*"

ignoreregex =
