# ------------------------------------------------------------------------------
# monitor_gateway/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: nginx
    tasks_from: install-service

- ansible.builtin.import_tasks: create-site.yml
