{
 "title": "Home",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Live websites",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "bennerleyviaduct.org.uk",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket:\"monitor\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"http_response\" and r._field == \"result_type\" and r.server == \"https://www.bennerleyviaduct.org.uk\")\n  |> drop(columns:[\"_start\",\"_stop\",\"_field\",\"_measurement\",\"host\",\"method\",\"server\"])\n  |> map(fn: (r) =>({\n       _time: r._time,\n       _value: if r._value == \"success\" and r.status_code == \"200\" then \"Ok\" else if r._value == \"success\" then r.status_code else r._value\n      }))\n"
      }
     ]
    },
    {
     "title": "varilink.co.uk",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 3, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket:\"monitor\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"http_response\" and r._field == \"result_type\" and r.server == \"https://www.varilink.co.uk\")\n  |> drop(columns:[\"_start\",\"_stop\",\"_field\",\"_measurement\",\"host\",\"method\",\"server\"])\n  |> map(fn: (r) =>({\n       _time: r._time,\n       _value: if r._value == \"success\" and r.status_code == \"200\" then \"Ok\" else if r._value == \"success\" then r.status_code else r._value\n      }))\n"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU (system + user)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\" and r.host == \"africa\")\n  |> drop(columns: [\"cpu\",\"_measurement\",\"_field\",\"_start\",\"_stop\"])"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\" and r.host == \"america\")\n  |> drop(columns: [\"cpu\",\"_measurement\",\"_field\",\"_start\",\"_stop\"])"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\" and r.host == \"antarctica\")\n  |> drop(columns: [\"cpu\",\"_measurement\",\"_field\",\"_start\",\"_stop\"])"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\" and r.host == \"atlantic\")\n  |> drop(columns: [\"cpu\",\"_measurement\",\"_field\",\"_start\",\"_stop\"])"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\" and r.host == \"jupiter\")\n  |> drop(columns: [\"cpu\",\"_measurement\",\"_field\",\"_start\",\"_stop\"])"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\" and r.host == \"mercury\")\n  |> drop(columns: [\"cpu\",\"_measurement\",\"_field\",\"_start\",\"_stop\"])"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory (percentage used)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host == \"africa\")"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host == \"america\")"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host == \"antarctica\")"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host == \"atlantic\")"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host == \"jupiter\")"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host == \"mercury\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk (percentage used)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "africa",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.host == \"africa\")\n  |> keep(columns: [\"device\",\"_time\",\"_value\"])\n  "
      }
     ]
    },
    {
     "title": "america",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.host == \"america\")\n  |> keep(columns: [\"device\",\"_time\",\"_value\"])\n  "
      }
     ]
    },
    {
     "title": "atlantic",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.host == \"atlantic\")\n  |> keep(columns: [\"device\",\"_time\",\"_value\"])\n  "
      }
     ]
    },
    {
     "title": "mercury",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.host == \"mercury\")\n  |> keep(columns: [\"device\",\"_time\",\"_value\"])\n  "
      }
     ]
    },
    {
     "title": "antarctica",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.host == \"antarctica\")\n  |> keep(columns: [\"device\",\"_time\",\"_value\"])\n  "
      }
     ]
    },
    {
     "title": "jupiter",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.host == \"jupiter\")\n  |> keep(columns: [\"device\",\"_time\",\"_value\"])\n  "
      }
     ]
    }
   ]
  },
  { "title": "Network (Kbps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "africa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"monitor\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_recv\")\n  |> filter(fn: (r) => r[\"host\"] == \"africa\")\n  |> filter(fn: (r) => r[\"interface\"] == \"br0\")\n  |> difference()\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({ r with _field: if r._field == \"bytes_recv\" then \"In\" else \"Out\",_value: (float(v: r._value)*8.0)/60000.0 }))\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n"
    }
   ]
  },
  {
   "title": "america",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"monitor\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_recv\")\n  |> filter(fn: (r) => r[\"host\"] == \"america\")\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\")\n  |> difference()\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({ r with _field: if r._field == \"bytes_recv\" then \"In\" else \"Out\",_value: (float(v: r._value)*8.0)/60000.0 }))\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n"
    }
   ]
  },
  {
   "title": "antarctica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"monitor\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_recv\")\n  |> filter(fn: (r) => r[\"host\"] == \"antarctica\")\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\")\n  |> difference()\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({ r with _field: if r._field == \"bytes_recv\" then \"In\" else \"Out\",_value: (float(v: r._value)*8.0)/60000.0 }))\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n"
    }
   ]
  },
  {
   "title": "atlantic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"monitor\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_recv\")\n  |> filter(fn: (r) => r[\"host\"] == \"atlantic\")\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\")\n  |> difference()\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({ r with _field: if r._field == \"bytes_recv\" then \"In\" else \"Out\",_value: (float(v: r._value)*8.0)/60000.0 }))\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n"
    }
   ]
  },
  {
   "title": "jupiter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"monitor\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_recv\")\n  |> filter(fn: (r) => r[\"host\"] == \"jupiter\")\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\")\n  |> difference()\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({ r with _field: if r._field == \"bytes_recv\" then \"In\" else \"Out\",_value: (float(v: r._value)*8.0)/60000.0 }))\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n"
    }
   ]
  },
  {
   "title": "mercury",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"monitor\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_recv\")\n  |> filter(fn: (r) => r[\"host\"] == \"mercury\")\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\")\n  |> difference()\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({ r with _field: if r._field == \"bytes_recv\" then \"In\" else \"Out\",_value: (float(v: r._value)*8.0)/60000.0 }))\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n"
    }
   ]
  }
 ]
}