{
 "title": "Internal Hosts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CPU Usage % (System + User)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\")\n  |> drop(columns: [\"cpu\",\"_measurement\",\"_field\",\"_start\",\"_stop\"])\n  |> group(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mem\" and\n    r._field == \"used_percent\"\n  )\n  |> drop(columns: [\"_measurement\",\"_field\",\"_start\",\"_stop\"])\n  |> group(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "% Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"monitor\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"disk\" and\n    r._field == \"used_percent\"\n  )\n  |> keep(columns: [\"host\",\"device\",\"_time\",\"_value\"])\n  |> group(columns: [\"host\",\"device\"])"
    }
   ]
  }
 ]
}