# ------------------------------------------------------------------------------
# mail_external/tasks/domain/exim.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: >-
        If we are using an external smarthost then configure an entry for the
        domain
      ansible.builtin.lineinfile:
        path: /etc/exim4/domain.passwd.client
        line: "\
          {{ domain_name }}:\
          {{ domain_smarthost_username }}:\
          {{ domain_smarthost_userpass }}\
          "
        regexp: "^{{ domain_name }}:"
      when: mta_configtype == 'smarthost'

    - name: Check if any domains have been registered as local domains yet
      ansible.builtin.command: "\
        grep \"^dc_other_hostnames=''$\" /etc/exim4/update-exim4.conf.conf"
      register: grep_other_hostnames
      failed_when: grep_other_hostnames.rc != 0 and grep_other_hostnames.rc != 1
      changed_when: false

    - name: Configure this domain as the first local domain
      # No domain names have yet been set for dc_other_hostnames, so set this
      # domain name as the first to be configured.
      ansible.builtin.lineinfile:
        path: /etc/exim4/update-exim4.conf.conf
        line: "dc_other_hostnames='{{ domain_name }}'"
        regexp: "^dc_other_hostnames='.*'$"
      when: grep_other_hostnames.rc == 0
      notify: Exim configuration changed

    - block:

        # At least one domain name is set for dc_other_hostnames, so check if
        # this domain name is one of them and if it isn't then add it to the
        # list of domain names set for dc_other_hostnames.

        - name: Check if the domain is already registered as a local domain
          ansible.builtin.shell: >-
            grep '^dc_other_hostnames=' /etc/exim4/update-exim4.conf.conf |
            grep {{ domain_name }}
          register: grep_domain
          failed_when: grep_domain.rc != 0 and grep_domain.rc != 1
          changed_when: false

        - name: Register the domain as a local domain if it isn't already
          ansible.builtin.lineinfile:
            path: /etc/exim4/update-exim4.conf.conf
            line: 'dc_other_hostnames=''\1;{{ domain_name }}'''
            regexp: '^dc_other_hostnames=''(.*)''$'
            backrefs: yes
          when: grep_domain.rc == 1
          notify: Exim configuration changed

      when: grep_other_hostnames.rc == 1

    - block:

        - name: Create folder to hold domain certificate and key for Exim
          ansible.builtin.file:
            path: /etc/exim4/domains/{{ domain_name }}
            state: directory

        - name: >-
            Generate a self-signed certificate if not using a certification
            authority for this domain
          # The openssl req options here are modelled on the exim-gencert
          # script, which in Debian is located at:
          # /usr/share/doc/exim4-base/examples/exim-gencert
          ansible.builtin.command:
            cmd: >-
              openssl req -x509 -newkey rsa:2048 -days 1095 -nodes
              -out /etc/exim4/domains/{{ domain_name }}/cert.pem
              -keyout /etc/exim4/domains/{{ domain_name }}/key.pem
              -subj '{{ subject }}'
            creates: /etc/exim4/domains/{{ domain_name }}/cert.pem
          vars:
            subject: |-
              /CN=smtp.{{ domain_name }}
              {%- if domain_country is defined %}
              /C={{ domain_country }}
              {%- endif %}
              {%- if domain_state is defined %}
              /ST={{ domain_state }}
              {%- endif %}
              {%- if domain_locality is defined %}
              /L={{ domain_locality }}
              {%- endif %}
              {%- if domain_organisation is defined %}
              /O={{ domain_organisation }}
              {%- endif %}
              {%- if domain_organisation_unit is defined %}
              /OU={{ domain_organisation_unit }}
              {%- endif %}

        - name: Give Debian-exim group read access to the key file
          ansible.builtin.file:
            path: /etc/exim4/domains/{{ domain_name }}/key.pem
            group: Debian-exim
            mode: g+r

      when: not mail_uses_ca

  become: yes
