# ------------------------------------------------------------------------------
# mail_external/tasks/configure-domain/roundcube.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Generate self-signed certificate if it isn't already installed
      ansible.builtin.command:
        cmd: >-
          openssl req -new -x509 -nodes -days 1095
          -out /etc/ssl/certs/{{
          ( 'webmail.' + domain_name ) | replace('.', '_')
          }}.pem
          -keyout /etc/ssl/private/{{
          ( 'webmail.' + domain_name ) | replace('.', '_')
          }}.key
          -subj '/CN=webmail.{{ domain_name }}'
        creates: >-
          /etc/ssl/certs/{{
          ( 'webmail.' + domain_name ) | replace('.', '_')
          }}

    - name: Make Roundcube Webmail's Nginx site configuration available
      ansible.builtin.template:
        src: webmail-nginx-site.j2
        dest: /etc/nginx/sites-available/webmail.{{ domain_name }}.conf
      notify: Nginx configuration changed

    - name: Enable Roundcube Webmail's Nginx site configuration
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/webmail.{{ domain_name }}.conf
        state: link
        src: /etc/nginx/sites-available/webmail.{{ domain_name }}.conf
      notify: Nginx configuration changed

  become: yes
