# ------------------------------------------------------------------------------
# php_fpm/handlers/main.yml
# ------------------------------------------------------------------------------

---

- name: Reload the PHP FPM configuration
  ansible.builtin.service:
    name: php8.2-fpm
    state: reloaded
  become: yes
  listen: PHP FPM configuration changed
