# ------------------------------------------------------------------------------
# nginx/handlers/main.yml
# ------------------------------------------------------------------------------

---

- block:

    # Nginx service handlers

    - name: Populate service facts
      ansible.builtin.service_facts:
      listen: Nginx configuration changed

    - name: Reload nginx configuration if nginx is running
      ansible.builtin.service:
        name: nginx
        state: reloaded
      when: ansible_facts['services']['nginx']['state'] == 'running'
      listen: Nginx configuration changed

    - name: Start nginx if it isn't running
      ansible.builtin.service:
        name: nginx
        state: started
      when: ansible_facts['services']['nginx']['state'] != 'running'
      listen: Nginx configuration changed

    # Fail2Ban service handlers

    # Reloading the fail2ban configuration is not enough. It seems to me that
    # this only reloads jail configuration that are already active and so it
    # doesn't pick up on jail configurations that have been added.

    - name: Restart fail2ban if it isn't running
      ansible.builtin.service:
        name: fail2ban
        state: restarted
      listen: Fail2Ban configuration changed

  become: yes
