# ------------------------------------------------------------------------------
# dns_api/tasks/create-or-update-address-records.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: get-domain-id.yml
  when: domain_id is not defined

- ansible.builtin.include_tasks: create-or-update-record.yml
  loop:
    - type: A
      target: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
    - type: AAAA
      target: "{{ hostvars[inventory_hostname].ansible_default_ipv6.address }}"
  loop_control:
    loop_var: required_record
