# ------------------------------------------------------------------------------
# dns_api/tasks/create-or-update-record.yml
# ------------------------------------------------------------------------------

---

- name: Test if the DNS record has already been created or not
  ansible.builtin.uri:
    url: "\
      https://api.linode.com/v4/domains/{{ domain_id }}/records?\
      page={{ list_records_result.json.page | default(0) | int + 1 }}"
    method: GET
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
  until: >-
    list_records_result.json.data
    | selectattr('name', 'equalto', wp_subdomain)
    | selectattr('type', 'equalto', required_record.type)
    or
    list_records_result.json.page | int + 1
    > list_records_result.json.pages | int
  retries: 5
  register: list_records_result

- set_fact:
    list_records_result: >-
      {{
        list_records_result
        | combine({
          'json': list_records_result.json
          | combine({
            'page': 0
          })
        })
      }}

- name: Create DNS record
  ansible.builtin.uri:
    url: "https://api.linode.com/v4/domains/{{ domain_id }}/records"
    method: POST
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
    body_format: json
    body:
      name: "{{ wp_subdomain }}"
      type: "{{ required_record.type }}"
      target: "{{ required_record.target }}"
  register: create_record_result
  changed_when: create_record_result.status == 200
  when: >-
    not list_records_result.json.data
    | selectattr('name', 'equalto', wp_subdomain)
    | selectattr('type', 'equalto', required_record.type)

- name: Update DNS record
  ansible.builtin.uri:
    url: "\
      https://api.linode.com/v4/domains/{{ domain_id }}/records/\
      {{ current_record.id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
    body_format: json
    body:
      name: "{{ wp_subdomain }}"
      type: "{{ required_record.type }}"
      target: "{{ required_record.target }}"
  when: >-
    list_records_result.json.data
    | selectattr('name', 'equalto', wp_subdomain)
    | selectattr('type', 'equalto', required_record.type)
    and
    required_record.target != current_record.target
  register: update_record_result
  changed_when: update_record_result.status == 200
  vars:
    current_record: >-
      {{
        list_records_result.json.data |
        selectattr('name', 'equalto', wp_subdomain) |
        selectattr('type', 'equalto', required_record.type) |
        first
      }}
