# ------------------------------------------------------------------------------
# dns_api/tasks/create-or-update-address-records.yml
# ------------------------------------------------------------------------------

---

- name: >-
    Get the page of domains from the Linode domains API that contains this
    project's domain
  ansible.builtin.uri:
    url: "\
      https://api.linode.com/v4/domains?\
      page={{ list_domains_result.attempts | default(0) | int + 1 }}"
    method: GET
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
  until: |-
    list_domains_result.json.data | selectattr('domain', 'equalto', domain_name)
  retries: 5
  register: list_domains_result

- name: Set a fact that contains this project's Linode domain identifier
  ansible.builtin.set_fact:
    domain_id: >-
      {{
        (list_domains_result.json.data |
        selectattr('domain', 'equalto', domain_name) | first ).id
      }}

- ansible.builtin.include_tasks: create-or-update-record.yml
  loop:
    - type: A
      target: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
    - type: AAAA
      target: "{{ hostvars[inventory_hostname].ansible_default_ipv6.address }}"
  loop_control:
    loop_var: required_record
