# ------------------------------------------------------------------------------
# dns_api/tasks/create-or-update-record.yml
# ------------------------------------------------------------------------------

# Creates or updates a DNS record after having determined which of those actions
# is required by doing a find for the record first. The hostname, type and
# target for the record MUST be provided. The TTL seconds for the record can be
# optionally provded and if omitted the Linode default of 604800 seconds will be
# used. Note that before using this task list the Linode domain_id must be
# established, which can be done using the get-domain-id.yml task list within
# this role.

---

- ansible.builtin.import_tasks: find-record.yml

- name: Create DNS record
  ansible.builtin.uri:
    url: "{{ dns_api_base_url }}/{{ domain_id }}/records"
    method: POST
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
    body_format: json
    body: >-
      {{
        {
          "name": dns_record_hostname,
          "type": dns_record_type,
          "target": dns_record_target,
          "ttl_sec": (dns_record_ttl_sec | default(86400) | int)
        } | to_json
      }}
  register: create_record_result
  changed_when: create_record_result.status == 200
  when: dns_record_id is not defined

- name: Update DNS record
  ansible.builtin.uri:
    url: "{{ dns_api_base_url }}/{{ domain_id }}/records/{{ dns_record_id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
    body_format: json
    body: >-
      {{
        {
          "name": dns_record_hostname,
          "type": dns_record_type,
          "target": dns_record_target,
          "ttl_sec": (dns_record_ttl_sec | default(86400) | int)
        } | to_json
      }}
  when: dns_record_id is defined and
    ( 
      dns_record_current_target != dns_record_target or
      dns_record_current_ttl_sec | int
        != dns_record_ttl_sec | default(86400) | int
    )
  register: update_record_result
  changed_when: update_record_result.status == 200
