# ------------------------------------------------------------------------------
# dns_api/tasks/create-or-update-record.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: find-record.yml

- name: Create DNS record
  ansible.builtin.uri:
    url: "{{ dns_api_base_url }}/{{ domain_id }}/records"
    method: POST
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
    body_format: json
    body:
      name: "{{ wp_subdomain }}"
      type: "{{ required_record.type }}"
      target: "{{ required_record.target }}"
  register: create_record_result
  changed_when: create_record_result.status == 200
  when: >-
    not list_records_result.json.data
    | selectattr('name', 'equalto', wp_subdomain)
    | selectattr('type', 'equalto', required_record.type)

- name: Update DNS record
  ansible.builtin.uri:
    url: "{{ dns_api_base_url }}/{{ domain_id }}/records/{{ dns_record_id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ dns_linode_key }}"
    body_format: json
    body:
      name: "{{ wp_subdomain }}"
      type: "{{ required_record.type }}"
      target: "{{ required_record.target }}"
  when: >-
    list_records_result.json.data
    | selectattr('name', 'equalto', wp_subdomain)
    | selectattr('type', 'equalto', required_record.type)
    and
    required_record.target != current_record.target
  register: update_record_result
  changed_when: update_record_result.status == 200
  vars:
    current_record: >-
      {{
        list_records_result.json.data |
        selectattr('name', 'equalto', wp_subdomain) |
        selectattr('type', 'equalto', required_record.type) |
        first
      }}
