# ------------------------------------------------------------------------------
# dns_api/tasks/delete-address-record.yml
# ------------------------------------------------------------------------------

# This is a convenience wrapper task list for the generic delete-record.yml
# task list. Unlike delete-record.yml, this one is specific to "address"
# records, by which we mean record types A and AAAA, for a hostname. Its
# function is to ensure that the delete operation is only carried out IF the
# IP address currently associated with the DNS record matches the target for
# deletion. This is to prevent incorrect deletions if we were for example to
# delete a website instance whose subdomain duplicated that of another website
# instance on another host, which can happen during migrations.

---

- ansible.builtin.import_tasks: find-record.yml

- ansible.builtin.import_tasks: delete-record.yml
  when: dns_record_current_target == dns_record_target
