# ------------------------------------------------------------------------------
# mta/tasks/configure-service.yml
# ------------------------------------------------------------------------------

# The mta role is a dependency for several other roles. As each of those other
# roles imports the mta role, they will configure it for their use. For most
# aspects of the configuration, the settings that

---

- name: Get the current value for dc_other_hostnames
  ansible.builtin.command: >-
    perl -n -e
    'print "$1" if /^dc_other_hostnames='\''(.*)'\''$/'
    /etc/exim4/update-exim4.conf.conf
  changed_when: false
  register: perl_result

  # When Exim is installed dc_other_hostnames is initially set to the empty
  # string. The hosts of the mail_external and mail_internal roles immediately
  # set it to the home domain when they configure Exim to their needs. When
  # projects then configure their mail service they add their domain to it. If
  # the install-services playbook is run again with the mail_external role in
  # scope and the current value of dc_other_hostnames is anything other than the
  # empty string or the home domain we know that at least one project has
  # already been configured and so we must NOT clobber its current value. Only
  # the host of the mail_external role can have a value other than the empty
  # string or the home domain.
- name: >-
    Set the mta_other_hostnames variable to the current value of
    dc_other_hostnames
  ansible.builtin.set_fact:
    mta_other_hostnames: "{{ perl_result.stdout }}"
  when: >-
    perl_result.stdout != ansible_hostname and
    perl_result.stdout != '' and
    perl_result.stdout != home_domain

- block:

    - name: Template out the Exim4 update-exim4.conf.conf file
      template:
        src: update-exim4.conf.conf.j2
        dest: /etc/exim4/update-exim4.conf.conf
      notify: Exim configuration changed

    - name: Template out the Exim4 mailname file
      ansible.builtin.template:
        src: mailname.j2
        dest: /etc/mailname
      notify: Exim configuration changed

    - name: Add line to /etc/exim4/passwd.client if credentials supplied
      ansible.builtin.lineinfile:
        path: /etc/exim4/passwd.client
        line: "\
          {{ mta_smarthost_hostname }}:\
          {{ mta_smarthost_username }}:\
          {{ mta_smarthost_userpass }}\
          "
        regex: "^{{ mta_smarthost_hostname }}:"
      when: mta_smarthost_username is defined

    - name: Redirect emails to root to the home domain admin user
      ansible.builtin.lineinfile:
        path: /etc/aliases
        line: "root: {{ admin_user }}"
      notify: Aliases changed

  become: yes
