# ------------------------------------------------------------------------------
# mta/handlers/aliases.yml
# ------------------------------------------------------------------------------

# Handler for the event "Aliases changed".

---

- name: Run the newaliases command when the aliases have changed
  ansible.builtin.command: newaliases
  listen: Aliases changed
  become: yes
