# ------------------------------------------------------------------------------
# mta/handlers/main.yml
# ------------------------------------------------------------------------------

# Default handlers file, which pulls in all handlers for an environment with a
# a service manager such as systemd.

---

- ansible.builtin.import_tasks: ./common.yml

- name: Reload the Exim configuration if it is running
  ansible.builtin.service:
    name: exim4
    state: reloaded
  become: yes
  listen: Exim configuration changed
