# ------------------------------------------------------------------------------
# mta/handlers/none.yml
# ------------------------------------------------------------------------------

# Empty handlers file so that this role can be imported without handlers.

---
